-- Better Auth's core and passkey tables are generated by `better-auth/db/migration`
-- before this migration runs. The foreign key keeps every workspace owned by a
-- real auth user, and the unique owner constraint makes creation idempotent.

CREATE TABLE IF NOT EXISTS workspace (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_user_id text NOT NULL UNIQUE REFERENCES "user" (id) ON DELETE CASCADE,
  name text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
